void init(int, int);
void shutDown(int return_code);
void drawPlayer();
void drawEn(int);
void drawWall();
void keyCallBack(int, int);
void draw(int, float, float, float, float);
void render();
void keyHandler();
void drawBackground();
void init_opengl();
void init_buttons();
void moveEn();
void drawBeam();
void drawHit(double,double);
void shoot();
void updateEnemy();
